spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/producttest
    password: pacho
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update