spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/producttest
    password: root
    username: postgres

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
